# Generated by Django 4.2 on 2026-04-25 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='recursos/')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='cursos.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recursos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
