# Generated by Django 4.2 on 2026-03-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicituddocente',
            old_name='link_certificado',
            new_name='link_certificacion',
        ),
        migrations.RenameField(
            model_name='solicituddocente',
            old_name='mensaje',
            new_name='mensaje_motivacion',
        ),
    ]
