# Generated by Django 4.2 on 2026-05-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_biografia_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
